from django import forms

COUNTRY_CHOICES = [
    ('', 'Select your country'),
    ('afghanistan', 'Afghanistan'),
    ('albania', 'Albania'),
    ('algeria', 'Algeria'),
    ('american-samoa', 'American Samoa'),
    ('andorra', 'Andorra'),
    ('angola', 'Angola'),
    ('anguilla', 'Anguilla'),
    ('antarctica', 'Antarctica'),
    ('antigua-and-barbuda', 'Antigua and Barbuda'),
    ('argentina', 'Argentina'),
    ('armenia', 'Armenia'),
    ('aruba', 'Aruba'),
    ('australia', 'Australia'),
    ('austria', 'Austria'),
    ('azerbaijan', 'Azerbaijan'),
    ('bahamas', 'Bahamas'),
    ('bahrain', 'Bahrain'),
    ('bangladesh', 'Bangladesh'),
    ('barbados', 'Barbados'),
    ('belarus', 'Belarus'),
    ('belgium', 'Belgium'),
    ('belize', 'Belize'),
    ('benin', 'Benin'),
    ('bermuda', 'Bermuda'),
    ('bhutan', 'Bhutan'),
    ('bolivia', 'Bolivia'),
    ('bosnia-and-herzegovina', 'Bosnia and Herzegovina'),
    ('botswana', 'Botswana'),
    ('brazil', 'Brazil'),
    ('british-virgin-islands', 'British Virgin Islands'),
    ('brunei', 'Brunei'),
    ('bulgaria', 'Bulgaria'),
    ('burkina-faso', 'Burkina Faso'),
    ('burundi', 'Burundi'),
    ('cambodia', 'Cambodia'),
    ('cameroon', 'Cameroon'),
    ('canada', 'Canada'),
    ('cape-verde', 'Cape Verde'),
    ('cayman-islands', 'Cayman Islands'),
    ('central-african-republic', 'Central African Republic'),
    ('chad', 'Chad'),
    ('chile', 'Chile'),
    ('china', 'China'),
    ('colombia', 'Colombia'),
    ('comoros', 'Comoros'),
    ('cook-islands', 'Cook Islands'),
    ('costa-rica', 'Costa Rica'),
    ('croatia', 'Croatia'),
    ('cuba', 'Cuba'),
    ('curacao', 'Curaçao'),
    ('cyprus', 'Cyprus'),
    ('czech-republic', 'Czech Republic'),
    ('democratic-republic-of-the-congo', 'Democratic Republic of the Congo'),
    ('denmark', 'Denmark'),
    ('djibouti', 'Djibouti'),
    ('dominica', 'Dominica'),
    ('dominican-republic', 'Dominican Republic'),
    ('east-timor', 'East Timor'),
    ('ecuador', 'Ecuador'),
    ('egypt', 'Egypt'),
    ('el-salvador', 'El Salvador'),
    ('equatorial-guinea', 'Equatorial Guinea'),
    ('eritrea', 'Eritrea'),
    ('estonia', 'Estonia'),
    ('ethiopia', 'Ethiopia'),
    ('falkland-islands', 'Falkland Islands'),
    ('faroe-islands', 'Faroe Islands'),
    ('fiji', 'Fiji'),
    ('finland', 'Finland'),
    ('france', 'France'),
    ('french-guiana', 'French Guiana'),
    ('french-polynesia', 'French Polynesia'),
    ('gabon', 'Gabon'),
    ('gambia', 'Gambia'),
    ('georgia', 'Georgia'),
    ('germany', 'Germany'),
    ('ghana', 'Ghana'),
    ('gibraltar', 'Gibraltar'),
    ('greece', 'Greece'),
    ('greenland', 'Greenland'),
    ('grenada', 'Grenada'),
    ('guadeloupe', 'Guadeloupe'),
    ('guam', 'Guam'),
    ('guatemala', 'Guatemala'),
    ('guernsey', 'Guernsey'),
    ('guinea', 'Guinea'),
    ('guinea-bissau', 'Guinea-Bissau'),
    ('guyana', 'Guyana'),
    ('haiti', 'Haiti'),
    ('honduras', 'Honduras'),
    ('hong-kong', 'Hong Kong'),
    ('hungary', 'Hungary'),
    ('iceland', 'Iceland'),
    ('india', 'India'),
    ('indonesia', 'Indonesia'),
    ('iran', 'Iran'),
    ('iraq', 'Iraq'),
    ('ireland', 'Ireland'),
    ('isle-of-man', 'Isle of Man'),
    ('israel', 'Israel'),
    ('italy', 'Italy'),
    ('ivory-coast', 'Ivory Coast'),
    ('jamaica', 'Jamaica'),
    ('japan', 'Japan'),
    ('jersey', 'Jersey'),
    ('jordan', 'Jordan'),
    ('kazakhstan', 'Kazakhstan'),
    ('kenya', 'Kenya'),
    ('kiribati', 'Kiribati'),
    ('kosovo', 'Kosovo'),
    ('kuwait', 'Kuwait'),
    ('kyrgyzstan', 'Kyrgyzstan'),
    ('laos', 'Laos'),
    ('latvia', 'Latvia'),
    ('lebanon', 'Lebanon'),
    ('lesotho', 'Lesotho'),
    ('liberia', 'Liberia'),
    ('libya', 'Libya'),
    ('liechtenstein', 'Liechtenstein'),
    ('lithuania', 'Lithuania'),
    ('luxembourg', 'Luxembourg'),
    ('macau', 'Macau'),
    ('macedonia', 'Macedonia'),
    ('madagascar', 'Madagascar'),
    ('malawi', 'Malawi'),
    ('malaysia', 'Malaysia'),
    ('maldives', 'Maldives'),
    ('mali', 'Mali'),
    ('malta', 'Malta'),
    ('marshall-islands', 'Marshall Islands'),
    ('martinique', 'Martinique'),
    ('mauritania', 'Mauritania'),
    ('mauritius', 'Mauritius'),
    ('mayotte', 'Mayotte'),
    ('mexico', 'Mexico'),
    ('micronesia', 'Micronesia'),
    ('moldova', 'Moldova'),
    ('monaco', 'Monaco'),
    ('mongolia', 'Mongolia'),
    ('montenegro', 'Montenegro'),
    ('montserrat', 'Montserrat'),
    ('morocco', 'Morocco'),
    ('mozambique', 'Mozambique'),
    ('myanmar', 'Myanmar'),
    ('namibia', 'Namibia'),
    ('nauru', 'Nauru'),
    ('nepal', 'Nepal'),
    ('netherlands', 'Netherlands'),
    ('new-caledonia', 'New Caledonia'),
    ('new-zealand', 'New Zealand'),
    ('nicaragua', 'Nicaragua'),
    ('niger', 'Niger'),
    ('nigeria', 'Nigeria'),
    ('niue', 'Niue'),
    ('norfolk-island', 'Norfolk Island'),
    ('north-korea', 'North Korea'),
    ('northern-mariana-islands', 'Northern Mariana Islands'),
    ('norway', 'Norway'),
    ('oman', 'Oman'),
    ('pakistan', 'Pakistan'),
    ('palau', 'Palau'),
    ('palestine', 'Palestine'),
    ('panama', 'Panama'),
    ('papua-new-guinea', 'Papua New Guinea'),
    ('paraguay', 'Paraguay'),
    ('peru', 'Peru'),
    ('philippines', 'Philippines'),
    ('poland', 'Poland'),
    ('portugal', 'Portugal'),
    ('puerto-rico', 'Puerto Rico'),
    ('qatar', 'Qatar'),
    ('republic-of-the-congo', 'Republic of the Congo'),
    ('reunion', 'Réunion'),
    ('romania', 'Romania'),
    ('russia', 'Russia'),
    ('rwanda', 'Rwanda'),
    ('saint-barthelemy', 'Saint Barthélemy'),
    ('saint-helena', 'Saint Helena'),
    ('saint-kitts-and-nevis', 'Saint Kitts and Nevis'),
    ('saint-lucia', 'Saint Lucia'),
    ('saint-martin', 'Saint Martin'),
    ('saint-pierre-and-miquelon', 'Saint Pierre and Miquelon'),
    ('saint-vincent-and-the-grenadines', 'Saint Vincent and the Grenadines'),
    ('samoa', 'Samoa'),
    ('san-marino', 'San Marino'),
    ('sao-tome-and-principe', 'São Tomé and Príncipe'),
    ('saudi-arabia', 'Saudi Arabia'),
    ('senegal', 'Senegal'),
    ('serbia', 'Serbia'),
    ('seychelles', 'Seychelles'),
    ('sierra-leone', 'Sierra Leone'),
    ('singapore', 'Singapore'),
    ('sint-maarten', 'Sint Maarten'),
    ('slovakia', 'Slovakia'),
    ('slovenia', 'Slovenia'),
    ('solomon-islands', 'Solomon Islands'),
    ('somalia', 'Somalia'),
    ('south-africa', 'South Africa'),
    ('south-korea', 'South Korea'),
    ('south-sudan', 'South Sudan'),
    ('spain', 'Spain'),
    ('sri-lanka', 'Sri Lanka'),
    ('sudan', 'Sudan'),
    ('suriname', 'Suriname'),
    ('swaziland', 'Swaziland'),
    ('sweden', 'Sweden'),
    ('switzerland', 'Switzerland'),
    ('syria', 'Syria'),
    ('taiwan', 'Taiwan'),
    ('tajikistan', 'Tajikistan'),
    ('tanzania', 'Tanzania'),
    ('thailand', 'Thailand'),
    ('togo', 'Togo'),
    ('tokelau', 'Tokelau'),
    ('tonga', 'Tonga'),
    ('trinidad-and-tobago', 'Trinidad and Tobago'),
    ('tunisia', 'Tunisia'),
    ('turkey', 'Turkey'),
    ('turkmenistan', 'Turkmenistan'),
    ('turks-and-caicos-islands', 'Turks and Caicos Islands'),
    ('tuvalu', 'Tuvalu'),
    ('uganda', 'Uganda'),
    ('ukraine', 'Ukraine'),
    ('united-arab-emirates', 'United Arab Emirates'),
    ('united-kingdom', 'United Kingdom'),
    ('united-states', 'United States'),
    ('uruguay', 'Uruguay'),
    ('uzbekistan', 'Uzbekistan'),
    ('vanuatu', 'Vanuatu'),
    ('vatican-city', 'Vatican City'),
    ('venezuela', 'Venezuela'),
    ('vietnam', 'Vietnam'),
    ('wallis-and-futuna', 'Wallis and Futuna'),
    ('western-sahara', 'Western Sahara'),
    ('yemen', 'Yemen'),
    ('zambia', 'Zambia'),
    ('zimbabwe', 'Zimbabwe'),
    ('other', 'Other'),
]

PHONE_CODE_CHOICES = [
    ('+1', '+1'),
    ('+7', '+7'),
    ('+20', '+20'),
    ('+27', '+27'),
    ('+30', '+30'),
    ('+31', '+31'),
    ('+32', '+32'),
    ('+33', '+33'),
    ('+34', '+34'),
    ('+36', '+36'),
    ('+39', '+39'),
    ('+40', '+40'),
    ('+41', '+41'),
    ('+43', '+43'),
    ('+44', '+44'),
    ('+45', '+45'),
    ('+46', '+46'),
    ('+47', '+47'),
    ('+48', '+48'),
    ('+49', '+49'),
    ('+51', '+51'),
    ('+52', '+52'),
    ('+53', '+53'),
    ('+54', '+54'),
    ('+55', '+55'),
    ('+56', '+56'),
    ('+57', '+57'),
    ('+58', '+58'),
    ('+60', '+60'),
    ('+61', '+61'),
    ('+62', '+62'),
    ('+63', '+63'),
    ('+64', '+64'),
    ('+65', '+65'),
    ('+66', '+66'),
    ('+81', '+81'),
    ('+82', '+82'),
    ('+84', '+84'),
    ('+86', '+86'),
    ('+90', '+90'),
    ('+91', '+91'),
    ('+92', '+92'),
    ('+93', '+93'),
    ('+94', '+94'),
    ('+95', '+95'),
    ('+98', '+98'),
    ('+211', '+211'),
    ('+212', '+212'),
    ('+213', '+213'),
    ('+216', '+216'),
    ('+218', '+218'),
    ('+220', '+220'),
    ('+221', '+221'),
    ('+222', '+222'),
    ('+223', '+223'),
    ('+224', '+224'),
    ('+225', '+225'),
    ('+226', '+226'),
    ('+227', '+227'),
    ('+228', '+228'),
    ('+229', '+229'),
    ('+230', '+230'),
    ('+231', '+231'),
    ('+232', '+232'),
    ('+233', '+233'),
    ('+234', '+234'),
    ('+235', '+235'),
    ('+236', '+236'),
    ('+237', '+237'),
    ('+238', '+238'),
    ('+239', '+239'),
    ('+240', '+240'),
    ('+241', '+241'),
    ('+242', '+242'),
    ('+243', '+243'),
    ('+244', '+244'),
    ('+245', '+245'),
    ('+246', '+246'),
    ('+248', '+248'),
    ('+249', '+249'),
    ('+250', '+250'),
    ('+251', '+251'),
    ('+252', '+252'),
    ('+253', '+253'),
    ('+254', '+254'),
    ('+255', '+255'),
    ('+256', '+256'),
    ('+257', '+257'),
    ('+258', '+258'),
    ('+260', '+260'),
    ('+261', '+261'),
    ('+262', '+262'),
    ('+263', '+263'),
    ('+264', '+264'),
    ('+265', '+265'),
    ('+266', '+266'),
    ('+267', '+267'),
    ('+268', '+268'),
    ('+269', '+269'),
    ('+290', '+290'),
    ('+291', '+291'),
    ('+297', '+297'),
    ('+298', '+298'),
    ('+299', '+299'),
    ('+350', '+350'),
    ('+351', '+351'),
    ('+352', '+352'),
    ('+353', '+353'),
    ('+354', '+354'),
    ('+355', '+355'),
    ('+356', '+356'),
    ('+357', '+357'),
    ('+358', '+358'),
    ('+359', '+359'),
    ('+370', '+370'),
    ('+371', '+371'),
    ('+372', '+372'),
    ('+373', '+373'),
    ('+374', '+374'),
    ('+375', '+375'),
    ('+376', '+376'),
    ('+377', '+377'),
    ('+378', '+378'),
    ('+379', '+379'),
    ('+380', '+380'),
    ('+381', '+381'),
    ('+382', '+382'),
    ('+383', '+383'),
    ('+385', '+385'),
    ('+386', '+386'),
    ('+387', '+387'),
    ('+389', '+389'),
    ('+420', '+420'),
    ('+421', '+421'),
    ('+423', '+423'),
    ('+500', '+500'),
    ('+501', '+501'),
    ('+502', '+502'),
    ('+503', '+503'),
    ('+504', '+504'),
    ('+505', '+505'),
    ('+506', '+506'),
    ('+507', '+507'),
    ('+508', '+508'),
    ('+509', '+509'),
    ('+590', '+590'),
    ('+591', '+591'),
    ('+592', '+592'),
    ('+593', '+593'),
    ('+594', '+594'),
    ('+595', '+595'),
    ('+596', '+596'),
    ('+597', '+597'),
    ('+598', '+598'),
    ('+599', '+599'),
    ('+670', '+670'),
    ('+672', '+672'),
    ('+673', '+673'),
    ('+674', '+674'),
    ('+675', '+675'),
    ('+676', '+676'),
    ('+677', '+677'),
    ('+678', '+678'),
    ('+679', '+679'),
    ('+680', '+680'),
    ('+681', '+681'),
    ('+682', '+682'),
    ('+683', '+683'),
    ('+684', '+684'),
    ('+685', '+685'),
    ('+686', '+686'),
    ('+687', '+687'),
    ('+688', '+688'),
    ('+689', '+689'),
    ('+690', '+690'),
    ('+691', '+691'),
    ('+692', '+692'),
    ('+850', '+850'),
    ('+852', '+852'),
    ('+853', '+853'),
    ('+855', '+855'),
    ('+856', '+856'),
    ('+880', '+880'),
    ('+886', '+886'),
    ('+960', '+960'),
    ('+961', '+961'),
    ('+962', '+962'),
    ('+963', '+963'),
    ('+964', '+964'),
    ('+965', '+965'),
    ('+966', '+966'),
    ('+967', '+967'),
    ('+968', '+968'),
    ('+970', '+970'),
    ('+971', '+971'),
    ('+972', '+972'),
    ('+973', '+973'),
    ('+974', '+974'),
    ('+975', '+975'),
    ('+976', '+976'),
    ('+977', '+977'),
    ('+992', '+992'),
    ('+993', '+993'),
    ('+994', '+994'),
    ('+995', '+995'),
    ('+996', '+996'),
    ('+998', '+998'),
]

class ContactForm(forms.Form):
    name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Your name'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'name@example.com'}))
    organisation = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Organisation name'}))
    country = forms.ChoiceField(choices=COUNTRY_CHOICES, required=False, widget=forms.Select())
    phone_code = forms.ChoiceField(choices=PHONE_CODE_CHOICES, required=False, widget=forms.Select())
    phone = forms.CharField(max_length=20, required=False, widget=forms.TextInput(attrs={'placeholder': 'Phone number'}))
    help = forms.ChoiceField(choices=[
        ('', 'Select an option'),
        ('project-design', 'Project Design & Feasibility'),
        ('implementation', 'Implementation Support'),
        ('m-e', 'Monitoring & Evaluation'),
        ('capacity-building', 'Capacity Building'),
        ('partnership', 'Partnership Opportunities'),
        ('other', 'Other'),
    ], required=False, widget=forms.Select())
    message = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Tell us about your initiative...'}))